title: Recopilación recursos frente Pandemias
description: >- # this means to ignore newlines until "theme:"
  Sitio de recopilación de recursos frente a pandemias, específicamente creado para COVID-19. 
  Accede y comparte recursos, makers u organizaciones.
theme: jekyll-theme-cayman
